name: Pull Request Quality Checks

permissions:
  actions: read
  contents: read

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'npm'
      - run: npm ci
      - uses: nrwl/nx-set-shas@v3
      - run: git branch --track main origin/main
      - run: npx nx affected --target=lint --base=origin/main
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'npm'
      - run: npm ci
      - uses: nrwl/nx-set-shas@v3
      - run: git branch --track main origin/main
      - run: npx nx format:check --base=origin/main
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'npm'
      - run: npm ci
      - uses: nrwl/nx-set-shas@v3
      - run: git branch --track main origin/main
      - run: npx nx affected --target=build --base=origin/main
